apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: output-volume
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: git-volume
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: build-script
data:
  build-script.sh: |
    #!/bin/sh
    apt-get update
    apt-get install -y git make curl
    curl -L https://github.com/gohugoio/hugo/releases/download/v0.111.2/hugo_extended_0.111.2_linux-amd64.deb -o hugo.deb
    apt install ./hugo.deb
    cd git
    git clone https://github.com/chazapis/hy548.git
    cd hy548
    git submodule init
    git submodule update
    make
    cp -R html/public/* ../../html-files

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: rebuild-script
data:
  rebuild-script.sh: |
    #!/bin/sh
    apt-get update
    apt-get install -y git make curl
    cd git/hy548
    if [ -n "$(git status --porcelain)" ]; then
      git pull
      curl -L https://github.com/gohugoio/hugo/releases/download/v0.111.2/hugo_extended_0.111.2_linux-amd64.deb -o hugo.deb
      apt install ./hugo.deb
      make 
      cp -R html/public/* ../../html-files
      echo The website was updated successfully
    else
      echo No changes were made
    fi

---
apiVersion: batch/v1
kind: Job
metadata:
  name: build
spec:
  template:
    metadata:
      name: build-website
    spec:
      restartPolicy: OnFailure
      containers:
      - name: ubuntu
        image: ubuntu:20.04
        command: ["/bin/sh", "-c", "./config/build-script.sh"]
        volumeMounts:
        - name: config-volume
          mountPath: "/config"
        - name: output-volume
          mountPath: "/html-files"
        - name: git-volume
          mountPath: "/git"
      volumes:
      - name: config-volume
        configMap:
          name: build-script
          defaultMode: 0777
      - name: output-volume
        persistentVolumeClaim:
          claimName: output-volume
      - name: git-volume
        persistentVolumeClaim:
          claimName: git-volume

---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: rebuild
spec:
  schedule: "15 2 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: rebuild-site
              image: ubuntu:20.04
              command: ["/bin/sh", "-c", "./config/rebuild-script.sh"]
              volumeMounts:
                - name: config-volume
                  mountPath: /config
                - name: output-volume
                  mountPath: /html-files
                - name: git-volume
                  mountPath: "/git"
          volumes:
            - name: config-volume
              configMap:
                name: rebuild-script
                defaultMode: 0777
            - name: output-volume
              persistentVolumeClaim:
                claimName: output-volume
            - name: git-volume
              persistentVolumeClaim:
                claimName: git-volume                
          restartPolicy: OnFailure

---
apiVersion: v1
kind: Pod
metadata:
  name: local548
spec:
  containers:
  - name: nginx-container
    image: nginx:1.23.3-alpine
    ports:
    - containerPort: 80
    volumeMounts:
    - name: output-volume 
      mountPath: usr/share/nginx/html
  volumes:
  - name: output-volume
    persistentVolumeClaim:
      claimName: output-volume